service:
  name: serverless-bonk-template

# Create an optimized package for our functions
package:
  individually: true

resources:
  # DynamoDB tables
  - ${file(resources/example-table.yaml)}

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:ENV}
  region: ${env:REGION}
  lambdaHashingVersion: 20201221
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  ${file(src/functions/example/exmaple.yaml)}
