service:
  name: translate-me

# Create an optimized package for our functions
package:
  individually: true

resources:
  # DynamoDB tables
  - ${file(resources/users-dynamo-table.yaml)}
  - ${file(resources/email-dynamo-table.yaml)}

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { 'Fn::GetAtt': ['UsersTable', 'Arn'] }
        - { 'Fn::GetAtt': ['EmailsTable', 'Arn'] }
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  exampleFunction:
    handler: ./functions/example.main
    events:
      - http:
          path: /example
          method: get
          cors: true